name: pdslab
description: "Website for the Mitochondrial Biology Lab at Indian Institute of Science."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.0.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_generator: ^2.4.0
  riverpod_annotation: ^2.3.5
  json_serializable: ^6.7.1
  cupertino_icons: ^1.0.6
  path: ^1.9.0
  url_launcher: ^6.2.5
  smooth_page_indicator: ^1.1.0
  web: ^0.5.1
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.5.1
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0
  sanitize_html: ^2.1.0
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/bg/
    - lib/assets/icons/
    - lib/assets/fonts/
    - lib/assets/logos/    
    - lib/assets/data/about/
    - lib/assets/data/news/
    - lib/assets/data/notice/
    - lib/assets/data/notification/
    - lib/assets/data/research/
    - lib/assets/data/people/
    - lib/assets/data/publication/
    - lib/assets/data/research-area/
    - lib/assets/data/social-media/
    - lib/assets/data/contact/
    - lib/assets/data/funds/
    - lib/assets/data/research-area/
    - lib/assets/images/people/research/
    - lib/assets/images/people/
    - lib/assets/images/parallax/
    - lib/assets/images/album/
    - lib/assets/images/poster/
    - lib/assets/images/cards/
    - lib/assets/images/models/abishek-jcb/
    - lib/assets/images/models/gautam-elife/
    - lib/assets/images/gallery/
    - lib/assets/images/gallery/birthdays/2021/patrick_d_silva/
    - lib/assets/images/gallery/birthdays/2022/patrick_d_silva/
    - lib/assets/images/gallery/events/2020/centenary_celebration/
    - lib/assets/images/gallery/events/2021/diwali/
    - lib/assets/images/gallery/events/2022/bybc_jncasr/
    - lib/assets/images/gallery/events/2022/diwali/
    - lib/assets/images/gallery/events/2022/independance_day/
    - lib/assets/images/gallery/events/2022/nurturance_programme/
    - lib/assets/images/gallery/events/2022/sports_day/
    - lib/assets/images/gallery/farewell/2022/abhishek/
    - lib/assets/images/gallery/farewell/2022/tejashree/
    - lib/assets/images/gallery/lab_photos/
    - lib/assets/images/gallery/official_events/2018/sir_cv_raman_award/
    - lib/assets/images/gallery/official_events/2021/defence/abhishek/
    - lib/assets/images/gallery/official_events/2022/defence/tejashree/
    - lib/assets/images/gallery/official_events/2022/defence/vinaya/
