name: pdslab
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.2.3
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  riverpod_generator: ^2.6.3
  riverpod_annotation: ^2.6.1
  json_serializable: ^6.9.0
  cupertino_icons: ^1.0.8
  path: ^1.9.0
  url_launcher: ^6.2.4
  smooth_page_indicator: ^1.1.0
  web: ^1.1.0
  shared_preferences: ^2.5.1
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/bg/
    - lib/assets/icons/
    - lib/assets/fonts/
    - lib/assets/logos/    
    - lib/assets/data/about/
    - lib/assets/data/news/
    - lib/assets/data/notice/
    - lib/assets/data/notification/
    - lib/assets/data/research/
    - lib/assets/data/people/
    - lib/assets/data/publication/
    - lib/assets/data/research-area/
    - lib/assets/data/social-media/
    - lib/assets/data/contact/
    - lib/assets/data/funds/
    - lib/assets/data/research-area/
    - lib/assets/images/people/research/
    - lib/assets/images/people/
    - lib/assets/images/parallax/
    - lib/assets/images/album/
    - lib/assets/images/poster/
    - lib/assets/images/cards/
    - lib/assets/images/models/abishek-jcb/
    - lib/assets/images/models/gautam-elife/
    - lib/assets/images/gallery/
    - lib/assets/images/gallery/birthdays/2021/patrick_d_silva/
    - lib/assets/images/gallery/birthdays/2022/patrick_d_silva/
    - lib/assets/images/gallery/events/2020/centenary_celebration/
    - lib/assets/images/gallery/events/2021/diwali/
    - lib/assets/images/gallery/events/2022/bybc_jncasr/
    - lib/assets/images/gallery/events/2022/diwali/
    - lib/assets/images/gallery/events/2022/independance_day/
    - lib/assets/images/gallery/events/2022/nurturance_programme/
    - lib/assets/images/gallery/events/2022/sports_day/
    - lib/assets/images/gallery/farewell/2022/abhishek/
    - lib/assets/images/gallery/farewell/2022/tejashree/
    - lib/assets/images/gallery/lab_photos/
    - lib/assets/images/gallery/official_events/2018/sir_cv_raman_award/
    - lib/assets/images/gallery/official_events/2021/defence/abhishek/
    - lib/assets/images/gallery/official_events/2022/defence/tejashree/
    - lib/assets/images/gallery/official_events/2022/defence/vinaya/
  

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
